server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Маршрут для категорий
        - id: categories_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**
          filters:
            - RewritePath=/categories/(?<segment>.*), /categories/${segment}

        # Маршрут для админки категорий
        - id: admin_categories_route
          uri: lb://main-service
          predicates:
            - Path=/admin/categories/**
          filters:
            - RewritePath=/admin/categories/(?<segment>.*), /admin/categories/${segment}

        # Маршрут для админки комментариев
        - id: admin_comments_route
          uri: lb://main-service
          predicates:
            - Path=/admin/comments/**
          filters:
            - RewritePath=/admin/comments/(?<segment>.*), /admin/comments/${segment}

        # Маршрут для комментариев пользователя
        - id: user_comments_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/comments
            - Method=POST,GET
          filters:
            - RewritePath=/users/(?<userId>.*)/comments, /users/${userId}/comments

        # Маршрут для комментариев к событиям
        - id: event_comments_route
          uri: lb://main-service
          predicates:
            - Path=/events/{eventId}/comments
            - Method=POST,GET
          filters:
            - RewritePath=/events/(?<eventId>.*)/comments, /events/${eventId}/comments

        # Маршрут для админки компиляций
        - id: admin_compilations_route
          uri: lb://main-service
          predicates:
            - Path=/admin/compilations/**
          filters:
            - RewritePath=/admin/compilations/(?<segment>.*), /admin/compilations/${segment}

        # Маршрут для компиляций
        - id: compilations_route
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
          filters:
            - RewritePath=/compilations/(?<segment>.*), /compilations/${segment}

        # Маршрут для админки событий
        - id: admin_events_route
          uri: lb://main-service
          predicates:
            - Path=/admin/events/**
          filters:
            - RewritePath=/admin/events/(?<segment>.*), /admin/events/${segment}

        # Маршрут для событий пользователя
        - id: user_events_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/events
            - Method=POST,GET
          filters:
            - RewritePath=/users/(?<userId>.*)/events, /users/${userId}/events

        # Маршрут для событий
        - id: events_route
          uri: lb://main-service
          predicates:
            - Path=/events/**
          filters:
            - RewritePath=/events/(?<segment>.*), /events/${segment}

        # Маршрут для запросов пользователя
        - id: user_requests_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/requests
            - Method=POST,GET
          filters:
            - RewritePath=/users/(?<userId>.*)/requests, /users/${userId}/requests

        # Маршрут для админки пользователей
        - id: admin_users_route
          uri: lb://main-service
          predicates:
            - Path=/admin/users/**
          filters:
            - RewritePath=/admin/users/(?<segment>.*), /admin/users/${segment}