server:
  port: 0  # Случайный порт

stats:
  service:
    id: stats-service  # Имя сервиса в Eureka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_main
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Адрес Eureka Server
    register-with-eureka: true  # Регистрировать ли этот сервис в Eureka
    fetch-registry: true  # Получать ли информацию о других сервисах из Eureka
  instance:
    prefer-ip-address: true  # Использовать IP-адрес вместо hostname