server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:ewm-main-service
            - classpath:ewm-stats-server
            - classpath:gateway-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true