server:
  port: 9090

spring:
  application:
    name: ewm-stats-server
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10