spring:
  application:
    name: stats-server
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
logging:
  level:
    org.springframework.boot.web.embedded.tomcat: DEBUG
    org.springframework.web: DEBUG