server:
  port: 0

stat_server:
  uri: lb://stats-server

spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_stats
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
